networks:
  app_network:
    driver: bridge

volumes:
    clickhouse_data: {}
    clickhouse_log: {}
    grafana_data: {}

services:
  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    restart: unless-stopped
    network_mode: host
    depends_on:
      - clickhouse

  clickhouse:
    build:
      context: ./clickhouse
      dockerfile: Dockerfile
    container_name: clickhouse
    restart: always
    ports:
      - "9001:9000"
      - "8123:8123"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_log:/var/log/clickhouse-server
      #- ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml

  a2s-loader:
    build:
      context: ./a2s-loader
      dockerfile: Dockerfile
    container_name: a2s-loader
    restart: always
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - TIMEOUT=1
    depends_on:
      - clickhouse