apiVersion: 1

datasources:
  - name: clickhouse
    type: grafana-clickhouse-datasource
    typeName: ClickHouse
    typeLogoUrl: public/plugins/grafana-clickhouse-datasource/img/logo.svg
    access: proxy
    url: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData:
      port: 9001
      server: localhost
    readOnly: false