{
 "title": "A2S Server",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "address",
    "label": "Server",
    "query": "select distinct(address) as endpoint, server_name from a2s.info"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Connect Steam Link", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 1 }, "options": { "content": " " } },
  {
   "title": "Player Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, player_count\nFROM a2s.info i \nwhere $__timeFilter(timestamp) and address = '$address'\nORDER BY timestamp ASC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ((player_count+bot_count) / max_players) * 100\r\nFROM a2s.info i \r\nwhere $__timeFilter(timestamp) and address = '$address'\r\nORDER BY timestamp DESC\r\nLIMIT 1",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Current Minutes Played",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(duration)/60 as minutes from a2s.players \r\nwhere timestamp = (select max(timestamp) from a2s.players where $__timeFilter(timestamp) and address = '$address') and address = '$address'\r\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Currrent Players",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "rawSql": "select name as Name, score as Score, duration/60 as Minutes from a2s.players \r\nwhere timestamp = (select max(timestamp) from a2s.players where $__timeFilter(timestamp) and address = '$address') and address = '$address'\r\norder by score desc",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Server Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, server_name\nFROM a2s.info i \nWHERE  $__timeFilter(timestamp) and address = '$address'\nORDER BY timestamp DESC\nLIMIT 1",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Game",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, game\nFROM a2s.info i \nWHERE  $__timeFilter(timestamp) and address = '$address'\nORDER BY timestamp DESC\nLIMIT 1",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Players",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, CONCAT(player_count , '/',max_players) players\r\nFROM a2s.info i \r\nWHERE  $__timeFilter(timestamp) and address = '$address'\r\nORDER BY timestamp DESC\r\nLIMIT 1",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Player Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT player_count as players, bot_count as bots, max_players - (player_count-bot_count) as empty\r\nFROM a2s.info i \r\nwhere $__timeFilter(timestamp) and address = '$address'\r\nORDER BY timestamp DESC\r\nLIMIT 1",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Current Total Score",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\r\nSELECT timestamp, sum(score) as score\r\nFROM a2s.players p\r\nwhere $__timeFilter(timestamp) and address = '$address'\r\nGROUP BY  timestamp\r\nORDER BY timestamp ASC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Max Players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, max_players\nFROM a2s.info i \nwhere $__timeFilter(timestamp) and address = '$address'\nORDER BY timestamp ASC\n\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Platform",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    timestamp, \n    CASE \n        WHEN platform = 'w' THEN 'Windows' \n         WHEN platform = 'l' THEN 'Linux' \n        ELSE 'Unkown' \n    END AS platform\nFROM \n    a2s.info i \n    WHERE  $__timeFilter(timestamp) and address = '$address'\nORDER BY \n    timestamp DESC\nLIMIT 1;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Map Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, map_name\nFROM a2s.info i \nWHERE  $__timeFilter(timestamp) and address = '$address'\nORDER BY timestamp DESC\nLIMIT 1",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Password Protected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nSELECT timestamp,   CASE \n        WHEN password_protected = 1 THEN 'True' \n         WHEN password_protected = 0 THEN 'False' \n    END AS  password_protected\nFROM a2s.info i \nWHERE  $__timeFilter(timestamp) and address = '$address'\nORDER BY timestamp DESC\nLIMIT 1",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\n\nSELECT \n    timestamp, \n    CASE \n        WHEN server_type = 'd' THEN 'Dedicated' \n         WHEN server_type = 'l' THEN 'Non Dedicated' \n           WHEN server_type = 'p' THEN 'HLTV' \n        ELSE 'Unkown' \n    END AS platform\nFROM \n    a2s.info i \n    WHERE  $__timeFilter(timestamp) and address = '$address'\nORDER BY \n    timestamp DESC\nLIMIT 1;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Bot Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, bot_count\nFROM a2s.info i \nwhere $__timeFilter(timestamp) and address = '$address'\nORDER BY timestamp ASC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ping * 1000\r\nFROM a2s.info i \r\nwhere $__timeFilter(timestamp) and address = '$address'\r\nORDER BY timestamp ASC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Unique Players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct name) as count from a2s.players \r\nwhere  $__timeFilter(timestamp) and address = '$address'\r\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, version\nFROM a2s.info i \nWHERE  $__timeFilter(timestamp) and address = '$address'\nORDER BY timestamp DESC\nLIMIT 1",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "VAC Enabled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nSELECT timestamp,   CASE \n        WHEN vac_enabled = 1 THEN 'True' \n         WHEN vac_enabled = 0 THEN 'False' \n    END AS  vac_enabled\nFROM a2s.info i \nWHERE  $__timeFilter(timestamp) and address = '$address'\nORDER BY timestamp DESC\nLIMIT 1",
     "selectedFormat": 4
    }
   ]
  },
  { "title": "Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Players Score",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, sum(score) as score\r\nFROM a2s.players p\r\nwhere $__timeFilter(timestamp) and address = '$address'\r\nGROUP BY  timestamp\r\nORDER BY timestamp ASC\r\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, player_count , max_players , bot_count \r\nFROM a2s.info i \r\nwhere $__timeFilter(timestamp) and address = '$address'\r\nORDER BY timestamp ASC",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Maps",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, map_name\r\nFROM a2s.info i \r\nWHERE  $__timeFilter(timestamp) and address = '$address'\r\nORDER BY timestamp DESC\r\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Ping ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, ping*1000 as milliseconds\r\nFROM a2s.info i \r\nwhere $__timeFilter(timestamp) and address = '$address'\r\nORDER BY timestamp ASC",
     "selectedFormat": 4
    }
   ]
  }
 ]
}